# Generated by Django 6.0.7 on 2026-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='User', max_length=255),
            preserve_default=False,
        ),
    ]
