# Generated by Django 6.0.7 on 2026-07-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_payment_status_user_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
