# Generated by Django 6.0.7 on 2026-07-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0014_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterUploadedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, default='Unknown Candidate', max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_file', models.FileField(upload_to='recruiter_resumes/')),
                ('parsed_text', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('ats_score', models.IntegerField(default=0)),
                ('match_percentage', models.IntegerField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommendation', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_resumes', to='candidate.jobdescription')),
            ],
        ),
    ]
