# Generated by Django 6.0.7 on 2026-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruiteruploadedresume_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteruploadedresume',
            name='hired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruploadedresume',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruploadedresume',
            name='selected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiteruploadedresume',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Pending Review', 'Pending Review'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Offer Sent', 'Offer Sent'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending Review', max_length=20),
        ),
    ]
