# Generated by Django 6.0.7 on 2026-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='parsed_text',
            field=models.TextField(blank=True),
        ),
    ]
