# Generated by Django 6.0.7 on 2026-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidateprofile_parsed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='parsed_text',
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True),
        ),
    ]
