# Generated by Django 6.0.7 on 2026-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidateprofile_parsed_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
