# Generated by Django 6.0.7 on 2026-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
