# Generated by Django 6.0.7 on 2026-07-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
