# Generated by Django 6.0.7 on 2026-07-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_resume_ats_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='education_data',
        ),
    ]
