# Generated by Django 6.0.7 on 2026-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_rename_education_resume_education_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
