# Generated by Django 6.0.7 on 2026-07-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_resume_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
