# Generated by Django 6.0.7 on 2026-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_jobmatchanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
