# Generated by Django 6.0.7 on 2026-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_resume_ats_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
